# vi: set wm=0 ai ts=2 sw=2 expandtab:

# directories
carddir: cards
logfile: cah.log

# game information
min_players: 3
max_players: 10
hand_size: 10

# IRC information
default_channel: "#test"
server: "irc.muppetlabs.com"
port: 6667
my_nick: "pycardbot"

# text and localization
language: en

text:
  en:
    all_cards_played: "Everyone has played. Here are the entries:"
    double_join: "You are already in the game!"
    not_implemented: "This command is not yet implemented"
    player_list: "Players currently in the game: {players}"
    player_hand: "Your cards are: {cards}"
    player_played: "You played: {card}"
    game_not_started: "Game hasn't started yet"
    question_announcement: "Card: {card}"
    round_announcement: "Round {round_num}! {czar} is the card czar"
    round_start: "A new game is starting! Type join to get in."
    score_announcement: "The most horrible people: {scores}"
    status_announcement: "Status: {czar} is the czar. Waiting for {players} to play."
    winner_announcement: "Winner is: {player} with \"{card}\"  {player} gets one point, and now has {points} points"
    status:
      inactive: "No game is currently active. Type start to start a new game."
      wait_answers: "Waiting for {players} to play their answer. Card on the table is: {question}"
      wait_czar: "Waiting for {czar} to pick a winner. Hands played are:"
      wait_players: "Waiting for players to join. Need {num} more to start."
