# vi: set wm=0 ai ts=2 sw=2 expandtab:

carddir: cards
default_channel: \#test
server: irc.muppetlabs.com
my_nick: pycardbot
min_players: 3
max_players: 10
language: en
hand_size: 10

text:
  en:
    all_cards_played: "Everyone has played.  Here are the entries:"
    player_hand: "Your cards are: {cards}"
    player_played: "You played: {card}"
    round_announcement: "Round {round_num}!  {czar} is the card czar"
    question_announcement: "Card: {card}"
    winner_announcement: "Winner is: {player} with \"{card}\"  {player} gets one point, and now has {points} points"
    status_announcement: "Status: {czar} is the czar.  Waiting for {players} to play."
    round_start: "A new game is starting! Type join to get in."
    double_join: "You are already in the game!"
